### ISSUE TITLE
Cannot disable telemetry

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-redhat-telemetry#17]
Ii noticed it while testing with Ij Tekton. I have the telemetry set
 
![image](https://user-images.githubusercontent.com/49404737/111456217-01da1880-8717-11eb-97a8-7368c21745a5.png)

if i try to uncheck it and click `apply` nothing happens. If i close it and re-open it i found that the checkbox is still checked

**Comment by adietish** [comment]
@lstocchi: you cannot disable telemetry if you run from source, the file setting is overriden by the setting in the system properties. 
In `build.gradle` for intellij-tekton we have the following:
```
runIde {
    systemProperties['com.redhat.devtools.intellij.telemetry.mode'] = 'debug'
}
```
Any setting you provide via system properties will override the file settings. "send usage statistics" toggles the settings in the file at `~/.redhat/com.redhat.devtools.intellij.telemetry` and then gets overriden by the sys property that exists in `build.gradle.`
Maybe we should set the system properties, too when unchecking/checking the checkbox in the preferences?

**Comment by adietish** [comment]
filed #20
