### ISSUE TITLE
telemetry freezes (comment on marketplace)

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-redhat-telemetry#27]
The following bug report was left on the [marketplace](https://plugins.jetbrains.com/plugin/16209-telemetry-by-red-hat)

> I downloaded this plugin as I use a lot Quarkus and I love Quarkus and suddenly it become dependent of this one.
But this plugin has some major issues.
It started freezing my IDE from time to time. And there is no place I can find any information to track or share for solution.
So I had to do what made me suffer almost as much as the problem it as causing.
I unninstalled it ....and had to uninstall the quarkus plugin too.
Sad... hope it improves soon or at least removes the dependency from the quarkus plugin

**Comment by adietish** [comment]
* I have no idea how and when telemetry freezes the IDE. Without steps it's rather hard to reproduce.
* the other issue is that one cannot uninstall telemetry and keep the requiring plugin, quarkus in this case

**Comment by lstocchi** [comment]
TBH I never experienced such a freeze but if you disable the telemetry, how would it be able to freeze the IDE? It should do nothing, right? Have you seen the quarkus logs on woopra? Any weird message?

**Comment by jeffmaury** [comment]
Please note that I suspect the Quarkus plugin because it has already had some freeze in the past and last version updated the LSP so may be related. Asking to get thread dump but not sure of the response

**Comment by adietish** [comment]
@jeffmaury and maybe ask the user to try to disable telemetry as @lstocchi pointed out?

**Comment by adietish** [comment]
@jeffmaury @lstocchi @sbouchet and then the question about turning telemetry optional?

**Comment by jeffmaury** [comment]
> 
> 
> @jeffmaury @lstocchi @sbouchet and then the question about turning telemetry optional?

Will make it immediately irrelevant and diverge from VSCode

**Comment by adietish** [comment]
Unfortunately the user didn't respond to our query for further informations and possibly a thread dump. That was 2 months ago, I'm thus resolving this issue.
