### ISSUE TITLE
~50% of users report no IDE version

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-redhat-telemetry#54]
Telemetry currently misses the IDE version for ~50% of our users.![grafik](https://user-images.githubusercontent.com/25126/171435690-b975b554-5bba-4f24-9b2b-47b0051cec5c.png)
This info is crucial because this tells what version most users use. This then allows us to know what acceptable minimal version to support. 

We collect the IDE name and version in [Environment](https://github.com/redhat-developer/intellij-redhat-telemetry/blob/main/src/main/java/com/redhat/devtools/intellij/telemetry/core/service/Environment.java#L100)

This queries [ApplicationNamesInfo.getFullProductName()](https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/openapi/application/ApplicationNamesInfo.java#L148)
Most likely we should query [ApplicationNamesInfo.getFullProductNameWithEdition()](https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/openapi/application/ApplicationNamesInfo.java#L164)

`ApplicationNamesInfo` parses the following file in the IDE: [IdeaApplicationInfo.xml](https://github.com/JetBrains/intellij-community/blob/master/community-resources/src/idea/IdeaApplicationInfo.xml)

**Comment by jeffmaury** [comment]
Yes
