### ISSUE TITLE
Add API for feedback only

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-redhat-telemetry#73]
As for now, feedback is purely using telemetry API to send feedback to our backend.
see https://github.com/redhat-developer/intellij-openshift-connector/issues/554#issuecomment-1623831346.

This as some drawbacks and limitations, because users may want to sent feedback and no telemetry usages. 
i proipose to create a separate API, specificquely for feedback, with  no opt-in/opt-out, because feedback means that users agree to send this inforamtion back to us.
Also, this might be a good idea to have a separate API if we change our feedback backend.

**Comment by adietish** [comment]
@sbouchet, @mohitsuman: if I get this right, feedback would not send startup, shutdown but it should send ide, plugin, os etc. correct?

**Comment by sbouchet** [comment]
> @sbouchet, @mohitsuman: Assuming that the user forbade telemetry and then sends feedback, would we still send the basic informations about the users setup like IDE, plugin, OS, etc.?

I think we should not. As a very strict user, i would only sent the values i've entered for the feedback.
if  it's only a value, (like a note), we should only send that note ( with a proper ID of course ) but nothing more.

this is'nt telemtry. just anonymous value.
